### ISSUE TITLE
How to build the latest fargate-cli

### ISSUE THREAD

**Issue by pahud** [pahud/fargate-samples#1]
## Why

As fargate-cli just [merged](https://github.com/jpignata/fargate/pull/62) a PR with extra regions support but not cut a new release yet. We need to manually build the `fargate-cli` at this moment.

## How

1. `git clone` the fargate-cli master branch
```
$ git clone https://github.com/jpignata/fargate.git
$ cd fargate
```

2.  `go build` the `fargate` binary with `golang:1.11` in docker

```
docker run -ti -v $PWD:/workdir -w /workdir golang:1.11 go mod init && make build                         
```

![image](https://user-images.githubusercontent.com/278432/48001839-b37adf00-e144-11e8-83cd-59c805a93597.png)

3. OK we got `bin/fargate` now

copy to `/usr/local/bin/fargate`

```
$ sudo cp bin/fargate /usr/local/bin/
```

**Comment by snese** [comment]
@pahud 

Using the cmd needs to setup the right $GOROOT and $GOPATH

> docker run -ti -v $PWD:/workdir -w /workdir golang:1.11 go mod init && make build

The run multiple commands in docker can avoid this issue that means all behaviors work in the container
`docker run -ti -v $PWD:/workdir -w /workdir golang:1.11 /bin/bash -c "go mod init && make build"`

**Comment by pahud** [comment]
@snese thanks for the feedback. I'll test it later and update the original content.
